Repository micronaut-projects/micronaut-multitenancy, pull requests merged in 2023-09, with the labels that each got.

#228 [multitenancy] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#232 test: add SubdomainTenantResolver tests
  multitenancy/src/test/groovy/io/micronaut/multitenancy/tenantresolver/SubdomainTenantResolverEnabledSpec.groovy
Labels: type: improvement

#233 docs: split docs in sections
  src/main/docs/guide/multitenancy.adoc
  src/main/docs/guide/multitenancy/installation.adoc
  src/main/docs/guide/multitenancy/tenantpropagation.adoc
  src/main/docs/guide/multitenancy/tenantresolvers.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs
